Add support for custom encoding/decoding.
RobotWebTools/roslibjs pull request #397
Opened 2021-02-02 18:48 UTC by J-Rojas

Adds encoder/decoder function options to `transportOptions`. This allows the caller to specify custom encoding and decoding functions.

2021-04-09 03:35 UTC, jihoonl approved these changes

2021-04-21 08:15 UTC, MatthijsBurgh requested changes

2021-04-21 08:15 UTC, MatthijsBurgh commented on src/core/SocketAdapter.js
> +    }
Unneeded change of whitespace

2021-04-22 16:36 UTC, J-Rojas commented on src/core/SocketAdapter.js
> +    }
Resolved.

2021-04-22 16:36 UTC, merged