Add `TF2Client`
RobotWebTools/roslibjs pull request #731
Opened 2024-05-29 21:43 UTC by pac48

This PR adds a `TF2Client` class to interact with the ROS 2 tf2_web_republisher.

2024-05-30 14:13 UTC, EzraBrooks requested changes
Thanks for working on this! Can you explain the API difference between your ROS 2 version of tf2_web_republisher and the ROS 1 version? If we can figure out a way to unify them (instead of renaming this `ROS2TFClient` or similar) that would be ideal!

2024-05-30 14:13 UTC, EzraBrooks commented on src/tf/TF2Client.js
> +export default class TF2Client extends EventEmitter {
I think this needs to be called something like `ROS2TFClient`, since "TF2" works on both ROS1 and ROS2.

2024-05-30 14:13 UTC, EzraBrooks commented on src/tf/TF2Client.js
> + */
lol
```suggestion
```

2024-05-30 14:13 UTC, EzraBrooks commented on src/tf/TF2Client.js
> +        // this.currentGoal.on('feedback', this.processTFArray.bind(this));
remove commented code

2024-05-30 14:13 UTC, EzraBrooks commented on src/tf/TF2Client.js
> +                console.log('Result for action goal on :');
let's not pollute the logs with debug info

2024-05-30 15:14 UTC, Hoffalypse commented on src/tf/TF2Client.js
> +        var nsecs = Math.floor((seconds - secs) * 1E9);
nitpicky but change these var to const

2024-06-10 15:09 UTC, EzraBrooks approved these changes
LGTM as a first cut. Naming it ROS2TFClient makes extra certain that we won't accidentally step on ROS 1 users' toes. Later on it may make sense to combine the two classes and use a flag, or something like that.

2024-06-10 15:11 UTC, EzraBrooks commented
For posterity, the "ROS 2 version of tf2_web_republisher" we are currently working against is @pac48's fork of it at https://github.com/pac48/tf2_web_republisher. We're still deciding where this should live long-term; it may become a ros2 branch of the RobotWebTools project that is largely currently defunct.

2024-06-10 15:15 UTC, merged

2024-06-18 17:28 UTC, pfarinha91 commented
Thanks for your work on this TF2 client for ROS2! 

I'm trying to make this approach work on a react application, but I'm struggling. I stumbled upon this thread and [this one](https://github.com/RobotWebTools/ros3djs/issues/658), changed the Roslibjs version on package.json to `github:pac48/roslibjs#pr-add-TF2Client`. Installed it and the rosbridge complained about not having the `send_action goal` operation. Basically actions are still not implemented on the main release of rosbridge for Ros Humble, which is behind the repository. So I cloned and compiled the most recent version of rosbridge, launched the websocket plus the tf2_web_republisher fork from @pac48 and I finally can subscribe to TFs and they start arriving through the callback! But...

**I can't unsubscribe or dispose the ROS2TFClient** when the parent React component unmounts (or in any moment whatsoever). Worst, the moment I subscribe to a new frame using the client, I no longer can unsubscribe from any topic (even in normal subscribers) and eventually `WebSocketClosedError: Tried to write to a closed websocket` errors start raining on the rosbridge websocket if I try to reconnect.

2024-06-18 17:33 UTC, EzraBrooks commented
Hi, that's interesting - I'm not experiencing the same symptom. Could you start a Discussion on this topic? I can provide some insight there as to integrating this with React (as my team is also using it with React), but would rather have that conversation in a Discussion than a PR thread so we can "mark as answer" when we find the solution :)

2024-06-18 17:34 UTC, EzraBrooks commented
I just realized Discussions weren't enabled here - I've enabled them!

2024-06-18 17:44 UTC, pfarinha91 commented
Thanks! Are you talking about discourse.ros.org? When I try to create a Discussion it redirects there.

2024-06-19 17:19 UTC, pfarinha91 commented
I've created the Discussion topic on https://github.com/RobotWebTools/roslibjs/discussions/742